# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f27c436bcda7965e4a83c35d49b614ef1204c002d6561071072d655fa997d137dfbb2ff1038dedbcc751a37531d6264b1a9ef718916a0d3f1db8c3158a88502

test:
  secret_key_base: b897e05d385020499fca9b15fbe7ba713be38468c434cc607c64a17bb7005c9bd3077182c9f24298e5d46272942865135a5ebd02262fddc30d214a19f6635330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
